export const LOADING = 'LOADING';
export const SET_BLOCKS = 'SET_BLOCKS';
export const SELECT_BLOCK = 'SELECT_BLOCK';
export const SET_ACCOUNT = 'SET_ACCOUNT';

export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const LOAD_BLOCKS_REQUEST = 'LOAD_BLOCKS_REQUEST';
export const SELECT_ACCOUNT_REQUEST = 'SELECT_ACCOUNT_REQUEST';
export const SELECT_ACCOUNT_SUCCESS = 'SELECT_ACCOUNT_SUCCESS';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
